[versions]
kotlin = "2.4.0"
asp-conventions = "20260701"
agp = "8.12.3"
antlr-kotlin = "1.0.12"
kotest = "5.9.1"
testballoon = "1.0.1-K2.4.0"

[libraries]
antlr-kotlin = { group = "com.strumenta", name = "antlr-kotlin-runtime", version.ref = "antlr-kotlin" }

[plugins]
asp-conventions = { id = "at.asitplus.gradle.conventions", version.ref = "asp-conventions" }
android-kmp-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
antlr-kotlin-plugin = { id = "com.strumenta.antlr-kotlin", version.ref = "antlr-kotlin" }
testballoon = { id = "de.infix.testBalloon", version.ref = "testballoon" }
