name: Publish Pages
on: workflow_dispatch
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  deploy-docs:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Common setup
        uses: a-sit-plus/internal-workflows/.github/actions/common-setup@v2
        with:
          java-version: '17'
          submodules: recursive
      - name: Build Dokka HTML
        run: ./gradlew dokkaHtml
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './build/dokka'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
